### PR TITLE
[FEATURE] Provide a cache context for bearer tokens

### PR DESCRIPTION
**Pull request by mariano-dagostino**

### CODE REVIEW

**Comment by e0ipso** [comment]
This is a fantastic PR!

I know tests are VERY lacking in this project, but I'd like to invite you to write a follow up PR for with a test.

Also, I'm looking for a co-maintainer for this module. Are you up to it @mariano-dagostino?

**Comment by mariano-dagostino** [comment]
Thanks! I will try to write a test soon. Also I'm ok to helping you as a comantainer.

**Comment by wimleers** [comment]
I don't understand why you need a cache context for this. This is the same as having a "session cookie" cache, which we also don't have.

There are sessions, and there are users. Whenever a user authenticates, they get a session. There can be a number of sessions per user (e.g. on multiple devices). There can never be multiple users for a given session.


---

`simple_oauth` simply provides you with an alternative mechanism for authenticating. So AFAICT you should be able to use either the `user` cache context, or the `session` cache context.

So why do you need a cache context for this?

**Comment by e0ipso** [comment]
This PR is a workaround. For some reason @mariano-dagostino was getting cache poisoning. I think that the culprit was that the context `user.permissions` was not being respected when authenticating with this authentication provider.

AFAICT if the authentication is successful, there should be nothing left for the authentication provider to make `user` cache contexts work.

One of the maintainers of Basic Auth in core, @juampynr, is also on the loop about this. Maybe he has some more context about this.

**Comment by juampynr** [comment]
No, I have no idea why this is happening.

**Comment by mariano-dagostino** [comment]
> There are sessions, and there are users. Whenever a user authenticates, they get a session. There can be a number of sessions per user (e.g. on multiple devices). There can never be multiple users for a given session.

I think the issue here is this module doesn't authenticate the user but just check the token is associated a certain permission to do something.

I didn't see any authenticate call like for example [Basic Auth](https://api.drupal.org/api/drupal/core%21modules%21basic_auth%21src%21Authentication%21Provider%21BasicAuth.php/function/BasicAuth%3A%3Aauthenticate/8.2.x) does.

**Comment by e0ipso** [comment]
@mariano-dagostino [here it is](https://github.com/e0ipso/simple_oauth/blob/8.x-1.x/src/Authentication/Provider/SimpleOauthAuthenticationProvider.php#L80-L100) the `authenticate` call.

**Comment by mariano-dagostino** [comment]
> This PR is a workaround. For some reason @mariano-dagostino was getting cache poisoning. I think that the culprit was that the context user.permissions was not being respected when authenticating with this authentication provider.

Reading all this thread again I think Wim' comment 

> I don't understand why you need a cache context for this. This is the same as having a "session cookie" cache, which we also don't have.

> There are sessions, and there are users. Whenever a user authenticates, they get a session. There can be a number of sessions per user (e.g. on multiple devices). There can never be multiple users for a given session.

Makes totally sense. My fix for this issue includes a cache tag for jsonapi here https://www.drupal.org/node/2817247 so probably by just adding 

`+    $cache_context[] = 'user.permission'; `

We may get the same result.

I won't be able to try this in the next two weeks.

**Pull request merged**
